# Generated by Django 2.2.6 on 2019-10-30 21:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('batch', models.PositiveSmallIntegerField(validators=[django.core.validators.RegexValidator('[0-9]{4}', message='Invalid Batch Year')], verbose_name='batch year')),
                ('arn', models.PositiveIntegerField(verbose_name='Admission Registration Number')),
                ('uid', models.CharField(default='00K-0000', help_text='University Student Roll Number', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[0-9]{2}[KLFICP]-[0-9]{4}', message='INVALID ROLL NUMBER FORMAT')], verbose_name='Student ID')),
                ('degree_name_enrolled', models.CharField(max_length=255, null=True)),
                ('degree_short_enrolled', models.CharField(max_length=30, null=True)),
                ('department_name_enrolled', models.CharField(max_length=255, null=True)),
                ('uni_mail', models.EmailField(max_length=254, null=True)),
                ('warning_count', models.PositiveSmallIntegerField(null=True)),
                ('attending_semester', models.BooleanField(help_text='If the student is currently attending classes', null=True)),
                ('student_year', models.SmallIntegerField(choices=[(1, 'FRESHMEN'), (2, 'SOPHOMORE'), (3, 'JUNIOR'), (4, 'SENIOR'), (5, 'VETERAN')], null=True)),
                ('current_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='initial.Semester')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
