# Generated by Django 2.2.7 on 2019-11-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_auto_20191112_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_section',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
