# Generated by Django 2.2.7 on 2019-11-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0004_auto_20191115_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
