# Generated by Django 2.2.7 on 2019-11-23 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0005_student_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='semester',
            new_name='semester_code',
        ),
    ]
