# Generated by Django 2.2 on 2020-05-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0038_auto_20200513_0031'),
        ('student_portal', '0007_auto_20200106_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(auto_now=True)),
                ('admission_fee', models.FloatField(default=0, max_length=20, null=True)),
                ('tution_fee', models.FloatField(default=0, max_length=20, null=True)),
                ('Fine', models.FloatField(default=0, max_length=20, null=True)),
                ('Arrear', models.FloatField(default=0, max_length=20, null=True)),
                ('withholding_tax', models.FloatField(default=0, max_length=20, null=True)),
                ('other_charges', models.FloatField(default=0, max_length=10, null=True)),
                ('coActivity_charges', models.FloatField(default=0, max_length=10, null=True)),
                ('total_fee', models.FloatField(default=0, max_length=20, null=True)),
                ('discount', models.FloatField(max_length=15)),
                ('financial_aid', models.FloatField(max_length=15)),
                ('courses', models.ManyToManyField(to='initial.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_portal.Student', verbose_name='Student Name')),
            ],
        ),
    ]
