# Generated by Django 2.2 on 2020-05-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0008_feechallan'),
    ]

    operations = [
        migrations.AddField(
            model_name='feechallan',
            name='challan_no',
            field=models.CharField(default='123456777', max_length=300),
        ),
    ]
