# Generated by Django 2.2 on 2020-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0010_auto_20200514_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='feechallan',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
