# Generated by Django 2.2 on 2020-05-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0011_feechallan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feechallan',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
