# Generated by Django 2.2.6 on 2019-10-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_auto_20191017_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.PositiveIntegerField(choices=[(1, 'Core'), (2, 'Elective'), (3, 'Elective (X)')], default=1, help_text='Core or Elective'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='credit_hour',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisites',
            field=models.ManyToManyField(to='initial.Course', verbose_name='Prerequisite Courses'),
        ),
    ]
