# Generated by Django 2.2.6 on 2019-10-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emergncy_contact',
            new_name='emergency_contact',
        ),
    ]
