# Generated by Django 2.2.6 on 2019-10-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(help_text='Name of University', max_length=255),
        ),
    ]
