# Generated by Django 2.2.5 on 2019-09-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='department',
            name='departemnt_name',
            field=models.CharField(help_text='Name of Department of Campus', max_length=255, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.PositiveIntegerField(help_text='Department ID', primary_key=True, serialize=False, verbose_name='Department ID'),
        ),
    ]
