# Generated by Django 2.2.6 on 2019-11-09 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_portal', '0001_initial'),
        ('teacher_portal', '0005_remove_teacher_department'),
        ('institution', '0003_auto_20191109_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='Address',
            new_name='campus_address',
        ),
        migrations.AddField(
            model_name='department',
            name='department_hod',
            field=models.ForeignKey(help_text='Current HOD of Department', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='department_students',
            field=models.ManyToManyField(to='student_portal.Student'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_teachers',
            field=models.ManyToManyField(to='teacher_portal.Teacher'),
        ),
    ]
