# Generated by Django 2.2.6 on 2019-10-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20190916_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='completion_year',
            field=models.PositiveSmallIntegerField(help_text='Years of Education after completion of degree', null=True),
        ),
        migrations.AddField(
            model_name='degree',
            name='degree_short',
            field=models.CharField(help_text='Short name Of Degree E.g : CS, BBA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='degree',
            name='duration',
            field=models.PositiveSmallIntegerField(help_text='Duration of Degree Program', null=True),
        ),
        migrations.AddField(
            model_name='degree',
            name='minimium_years_education',
            field=models.PositiveSmallIntegerField(help_text='minimium years of education required for admission in Degree', null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_name',
            field=models.CharField(help_text='Name Of Degree E.g: Computer Science(CS)', max_length=255, null=True, verbose_name='Degree Name'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='education_level',
            field=models.CharField(help_text='Education Level E.g: Bachelors, Masters, PhD', max_length=255, null=True, verbose_name='Education Level'),
        ),
    ]
