# Generated by Django 2.2.6 on 2019-11-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20191109_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together={('campus_name', 'campus_city')},
        ),
    ]
