# Generated by Django 2.2.6 on 2019-10-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20191016_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='id',
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_short',
            field=models.CharField(help_text='Short name Of Degree E.g : CS, BBA', max_length=255, primary_key=True, serialize=False),
        ),
    ]
