# Generated by Django 2.2.6 on 2019-11-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20191109_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(help_text='Name of Department of Campus', max_length=255, unique=True, verbose_name='Department Name'),
        ),
    ]
