# Generated by Django 2.2.7 on 2019-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_auto_20191109_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_students',
            field=models.ManyToManyField(related_name='students_in_department', to='student_portal.Student'),
        ),
    ]
