# Generated by Django 2.2.7 on 2019-11-12 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20191112_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='offering_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.Department'),
        ),
    ]
