# Generated by Django 2.2.7 on 2019-11-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_portal', '0001_initial'),
        ('institution', '0008_degree_offering_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_faculty',
            field=models.ManyToManyField(related_name='faculty_in_department', to='faculty_portal.Faculty'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_teachers',
            field=models.ManyToManyField(related_name='teachers_in_department', to='teacher_portal.Teacher'),
        ),
    ]
