# Generated by Django 2.2.7 on 2019-11-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0003_student_admission_section'),
        ('institution', '0009_auto_20191113_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_batch', models.CharField(blank=True, max_length=25, null=True)),
                ('batch', models.CharField(max_length=256)),
                ('section', models.CharField(help_text='Section Name Etc A,B,C etc', max_length=10)),
                ('students', models.ManyToManyField(to='student_portal.Student')),
            ],
            options={
                'unique_together': {('batch', 'section')},
            },
        ),
    ]
