# Generated by Django 2.2.7 on 2019-11-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0010_batchsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='registrations_open',
            field=models.BooleanField(blank=True, default=False, help_text='True if Course Registrations are Open, else False', null=True),
        ),
        migrations.AlterField(
            model_name='batchsection',
            name='sec_batch',
            field=models.CharField(blank=True, help_text='pk', max_length=25, null=True),
        ),
    ]
