# Generated by Django 2.2.7 on 2019-11-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_degree_registration_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsection',
            name='limit',
            field=models.SmallIntegerField(blank=True, default=40, null=True),
        ),
    ]
