# Generated by Django 2.2.5 on 2019-10-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_auto_20190929_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'Faculty Supervisors'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-pk',)},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='id',
        ),
        migrations.AddField(
            model_name='semester',
            name='semester_code',
            field=models.CharField(default='TEST2000', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='student',
            name='degree_name_enrolled',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='degree_short_enrolled',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department_name_enrolled',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='uni_mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_city',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_country',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_home_phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_postal_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergncy_contact',
            field=models.PositiveIntegerField(null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_contact',
            field=models.PositiveIntegerField(null=True, verbose_name='Mobile Contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_city',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_country',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_home_phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_postal_code',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
