# Generated by Django 2.2.5 on 2019-10-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0004_auto_20191010_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='semester_code',
        ),
        migrations.AddField(
            model_name='semester',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
