# Generated by Django 2.2.6 on 2019-11-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='educational_history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='actor.EducationalHistory', verbose_name='Educational Histories'),
        ),
    ]
