# Generated by Django 2.2.7 on 2019-11-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_auto_20191109_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('designation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=False, help_text='True if the User is a Employee of Institution'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('hire_date', models.DateField(null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('employee_designation', models.ManyToManyField(null=True, to='actor.EmployeeDesignation')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='actor.Employee'),
        ),
    ]
