# Generated by Django 2.2.7 on 2019-11-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_auto_20191112_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_designation',
            field=models.ManyToManyField(to='actor.EmployeeDesignation'),
        ),
    ]
