# Generated by Django 2.2.7 on 2019-11-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_auto_20191113_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
