# Generated by Django 2.2 on 2020-04-15 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0006_auto_20191113_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Date of Birth'),
        ),
    ]
