# Generated by Django 2.2 on 2020-05-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0007_auto_20200415_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergency_contact',
            field=models.PositiveIntegerField(default=923293571854, null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_contact',
            field=models.PositiveIntegerField(default=923293571855, null=True, verbose_name='Mobile Contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Pakistani', max_length=100, null=True, verbose_name='Nationality'),
        ),
    ]
