# Generated by Django 2.2.5 on 2019-09-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(help_text='Name of Univeristy', max_length=255),
        ),
    ]
