# Generated by Django 2.2.5 on 2019-09-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='arn',
        ),
    ]
