# Generated by Django 2.2.5 on 2019-09-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_remove_student_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='arn',
            field=models.PositiveIntegerField(default=1234, verbose_name='Admission Registration Number'),
            preserve_default=False,
        ),
    ]
