# Generated by Django 2.2.5 on 2019-09-16 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_student_arn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.CharField(default='00K-0000', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[0-9]{2}[ILKPFC]-[0-9]{4}', message='INVALID ROLL NUMBER FORMAT')], verbose_name='Student ID'),
        ),
    ]
