# Generated by Django 2.2.6 on 2019-10-10 20:34

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('U', 'UNDEFINED'), ('O', 'OTHER')], max_length=50, verbose_name='Gender')),
                ('is_teacher', models.BooleanField(default=False, help_text='True if the User is a Teacher.')),
                ('is_student', models.BooleanField(default=False, help_text='True if the User is a Student.')),
                ('is_faculty', models.BooleanField(default=False, help_text='True if the User is a Faculty Member.')),
                ('is_maintainer', models.BooleanField(default=False, help_text='True if the User is a Mainatiner or Project Developer.')),
                ('CNIC', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[0-9]{5}-[0-9]{7}-[0-9]{1}', message='Invalid CNIC')])),
                ('permanent_address', models.TextField(null=True)),
                ('permanent_home_phone', models.PositiveIntegerField(null=True)),
                ('permanent_postal_code', models.PositiveIntegerField(null=True)),
                ('permanent_city', models.TextField(max_length=100, null=True)),
                ('permanent_country', models.TextField(max_length=100, null=True)),
                ('current_address', models.TextField(null=True)),
                ('current_home_phone', models.PositiveIntegerField(null=True)),
                ('current_postal_code', models.PositiveIntegerField(null=True)),
                ('current_city', models.TextField(max_length=100, null=True)),
                ('current_country', models.TextField(max_length=100, null=True)),
                ('DOB', models.DateField(null=True, verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=100, null=True, verbose_name='Nationality')),
                ('mobile_contact', models.PositiveIntegerField(null=True, verbose_name='Mobile Contact')),
                ('emergency_contact', models.PositiveIntegerField(null=True, verbose_name='Emergency Contact')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_short', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('nu_email', models.CharField(max_length=100)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('batch', models.PositiveSmallIntegerField(validators=[django.core.validators.RegexValidator('[0-9]{4}', message='Invalid Batch Year')], verbose_name='batch year')),
                ('arn', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Admission Registration Number')),
                ('uid', models.CharField(default='00K-0000', help_text='University Student Roll Number', max_length=8, validators=[django.core.validators.RegexValidator('[0-9]{2}[KLFICP]-[0-9]{4}', message='INVALID ROLL NUMBER FORMAT')], verbose_name='Student ID')),
                ('degree_name_enrolled', models.CharField(max_length=255, null=True)),
                ('degree_short_enrolled', models.CharField(max_length=30, null=True)),
                ('department_name_enrolled', models.CharField(max_length=255, null=True)),
                ('uni_mail', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_code', models.CharField(default='TEST2000', max_length=255, primary_key=True, serialize=False)),
                ('semester_season', models.SmallIntegerField(choices=[(1, 'FALL'), (2, 'SPRING'), (3, 'SUMMER')])),
                ('Semester Year', models.DateField()),
                ('Semester Start Date', models.DateField()),
                ('Semester End Date', models.DateField()),
                ('offered_courses', models.ManyToManyField(related_name='semester_offered', to='initial.Course')),
                ('students_registered', models.ManyToManyField(related_name='students_registered', to='initial.Student')),
                ('teachers_available', models.ManyToManyField(related_name='teachers_available', to='initial.Teacher')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty Supervisors',
                'ordering': ('-pk',),
            },
        ),
    ]
