# Generated by Django 2.2.5 on 2019-09-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('department', models.CharField(max_length=10)),
                ('nu_email', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
