# Generated by Django 2.2.5 on 2019-09-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='nu_email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
