# Generated by Django 2.2.5 on 2019-09-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20190910_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_short', models.CharField(max_length=50)),
            ],
            options={
                'managed': 'True',
            },
        ),
    ]
