# Generated by Django 2.2.5 on 2019-09-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
    ]
