# Generated by Django 2.2.5 on 2019-09-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0004_auto_20190910_0256'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
