# Generated by Django 2.2.5 on 2019-09-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0005_auto_20190910_0256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
    ]
