# Generated by Django 2.2.6 on 2019-10-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_short', models.CharField(max_length=50)),
                ('credit_hour', models.PositiveSmallIntegerField(null=True)),
                ('course_type', models.PositiveIntegerField(choices=[(1, 'Core'), (2, 'Elective'), (3, 'Elective (X)')], help_text='Core or Elective')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='RegularCoreCourseLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_season', models.SmallIntegerField(choices=[(1, 'FALL'), (2, 'SPRING'), (3, 'SUMMER')])),
                ('credit_hour_limit', models.PositiveSmallIntegerField(default=19)),
                ('student_year', models.SmallIntegerField(choices=[(1, 'FRESHMEN'), (2, 'SOPHOMORE'), (3, 'JUNIOR'), (4, 'SENIOR'), (5, 'VETERAN')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_code', models.CharField(default='TEST2000', max_length=255, primary_key=True, serialize=False)),
                ('semester_season', models.SmallIntegerField(choices=[(1, 'FALL'), (2, 'SPRING'), (3, 'SUMMER')])),
                ('semester_year', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('offered_courses', models.ManyToManyField(related_name='semester_offered', to='initial.Course')),
            ],
        ),
    ]
