# Generated by Django 2.2.5 on 2019-09-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_short', models.CharField(max_length=50)),
            ],
        ),
    ]
