# Generated by Django 2.2.6 on 2019-10-30 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_portal', '0001_initial'),
        ('student_portal', '0001_initial'),
        ('initial', '0001_initial'),
        ('institution', '0002_auto_20191030_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='students_registered',
            field=models.ManyToManyField(related_name='students_registered', to='student_portal.Student'),
        ),
        migrations.AddField(
            model_name='semester',
            name='teachers_available',
            field=models.ManyToManyField(related_name='teachers_available', to='teacher_portal.Teacher'),
        ),
        migrations.AddField(
            model_name='regularcorecourseload',
            name='courses',
            field=models.ManyToManyField(to='initial.Course'),
        ),
        migrations.AddField(
            model_name='regularcorecourseload',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.Degree'),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisites',
            field=models.ManyToManyField(to='initial.Course', verbose_name='Prerequisite Courses'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('semester_season', 'semester_year')},
        ),
    ]
