# Generated by Django 2.2.6 on 2019-10-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_auto_20191016_1343'),
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularCoreCourseLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_season', models.SmallIntegerField(choices=[(1, 'FALL'), (2, 'SPRING'), (3, 'SUMMER')])),
                ('credit_hour_limit', models.PositiveSmallIntegerField(default=19)),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='initial.Course')),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.Degree')),
            ],
        ),
        migrations.DeleteModel(
            name='RegularCourseLoad',
        ),
    ]
