# Generated by Django 2.2.6 on 2019-11-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20191030_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularElectiveCourseLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_season', models.SmallIntegerField(choices=[(1, 'FALL'), (2, 'SPRING'), (3, 'SUMMER')])),
                ('courses', models.ManyToManyField(to='initial.Course')),
            ],
        ),
    ]
