# Generated by Django 2.2.6 on 2019-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20191016_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularcorecourseload',
            name='student_year',
            field=models.SmallIntegerField(choices=[(1, 'FRESHMEN'), (2, 'SOPHOMORE'), (3, 'JUNIOR'), (4, 'SENIOR')], null=True),
        ),
        migrations.RemoveField(
            model_name='regularcorecourseload',
            name='courses',
        ),
        migrations.AddField(
            model_name='regularcorecourseload',
            name='courses',
            field=models.ManyToManyField(to='initial.Course'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='offered_courses',
            field=models.ManyToManyField(related_name='semester_offered', to='initial.Course'),
        ),
    ]
