# Generated by Django 2.2.6 on 2019-11-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_auto_20191109_1724'),
        ('initial', '0003_regularelectivecourseload'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.Department'),
        ),
    ]
