# Generated by Django 2.2.5 on 2019-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0004_auto_20190910_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_season', models.SmallIntegerField(choices=[(1, 'FALL'), (2, 'SPRING'), (3, 'SUMMER')])),
                ('Semester Year', models.DateField()),
                ('Semester Start Date', models.DateField()),
                ('Semester End Date', models.DateField()),
                ('offered_courses', models.ManyToManyField(related_name='semester_offered', to='initial.Course')),
                ('students_registered', models.ManyToManyField(related_name='students_registered', to='initial.Student')),
                ('teachers_available', models.ManyToManyField(related_name='teachers_available', to='initial.Teacher')),
            ],
        ),
    ]
