# Generated by Django 2.2.6 on 2019-11-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0005_remove_teacher_department'),
        ('student_portal', '0001_initial'),
        ('initial', '0004_semester_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('state', models.CharField(choices=[('NR', 'Not Registered'), ('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('LV', 'Leave')], default='NR', max_length=256)),
                ('attendance_time', models.TimeField()),
                ('duration', models.SmallIntegerField(default=1)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_portal.Student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ManyToManyField(to='initial.Attendance')),
                ('students', models.ManyToManyField(to='student_portal.Student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_portal.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='initial.Course')),
                ('course_coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_coordinator_CourseClass', to='teacher_portal.Teacher')),
                ('sections', models.ManyToManyField(to='initial.CourseSection')),
                ('teachers', models.ManyToManyField(to='teacher_portal.Teacher')),
            ],
        ),
    ]
