# Generated by Django 2.2.6 on 2019-11-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0005_attendance_courseclass_coursesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='elective_course_load',
            field=models.ManyToManyField(to='initial.RegularElectiveCourseLoad'),
        ),
        migrations.AddField(
            model_name='semester',
            name='regualar_course_load',
            field=models.ManyToManyField(to='initial.RegularCoreCourseLoad'),
        ),
        migrations.CreateModel(
            name='RepeatCourseLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_season', models.SmallIntegerField(choices=[(1, 'FALL'), (2, 'SPRING'), (3, 'SUMMER')])),
                ('core_coursess', models.ManyToManyField(to='initial.RegularCoreCourseLoad')),
                ('elective_courses', models.ManyToManyField(to='initial.RegularElectiveCourseLoad')),
            ],
        ),
    ]
