# Generated by Django 2.2.5 on 2019-09-10 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0005_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CNIC',
            field=models.CharField(default=-1100001, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{5}-[0-9]{7}-[0-9]{3}$', message='Invalid CNIC')]),
            preserve_default=False,
        ),
    ]
