# Generated by Django 2.2.7 on 2019-11-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0006_auto_20191109_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='offered_courses',
        ),
    ]
