# Generated by Django 2.2.7 on 2019-11-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0007_remove_semester_offered_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='degree_short',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
