# Generated by Django 2.2.7 on 2019-11-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0009_auto_20191119_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='regualar_course_load',
            new_name='regular_course_load',
        ),
    ]
