# Generated by Django 2.2.7 on 2019-11-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0010_auto_20191119_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='CSDDC',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='initial.Course'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='semester_code',
            field=models.CharField(blank=True, help_text='semester code - SDDC', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='CSDDC',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='course_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='semester_code',
            field=models.CharField(blank=True, help_text='semester code - SDDC', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='course_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
