# Generated by Django 2.2.7 on 2019-11-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0011_auto_20191122_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='section_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
