# Generated by Django 2.2.7 on 2019-11-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0004_auto_20191115_0903'),
        ('initial', '0012_coursesection_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('R', 'Registered'), ('NR', 'Not Registered')], max_length=256, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_status_offer', to='initial.Course')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_code', models.CharField(blank=True, help_text='semester code - SDDC', max_length=256, null=True)),
                ('courses_offered', models.ManyToManyField(to='initial.CourseStatus')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_courses', to='student_portal.Student')),
            ],
            options={
                'unique_together': {('semester_code', 'student')},
            },
        ),
    ]
