# Generated by Django 2.2.7 on 2019-11-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0013_coursestatus_offeredcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestatus',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Registered'), ('NR', 'Not Registered')], default='NR', max_length=256, null=True),
        ),
    ]
