# Generated by Django 2.2.7 on 2019-11-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0014_auto_20191122_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularelectivecourseload',
            name='student_year',
            field=models.SmallIntegerField(choices=[(1, 'FRESHMEN'), (2, 'SOPHOMORE'), (3, 'JUNIOR'), (4, 'SENIOR'), (5, 'VETERAN')], null=True),
        ),
    ]
