# Generated by Django 2.2.7 on 2019-11-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0016_offeredcourses_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeredcourses',
            name='section',
        ),
        migrations.AddField(
            model_name='coursestatus',
            name='section',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
