# Generated by Django 2.2.7 on 2019-11-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0017_auto_20191123_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='section_seats',
            field=models.PositiveIntegerField(blank=True, default=40, null=True),
        ),
    ]
