# Generated by Django 2.2.7 on 2019-11-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0020_auto_20191123_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestatus',
            name='one_time_field',
        ),
    ]
