# Generated by Django 2.2.7 on 2019-11-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0022_coursestatus_one_time_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancesheet',
            old_name='sddc',
            new_name='scsddc',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='sddc',
            new_name='scsddc',
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='one_time_field',
            field=models.BooleanField(blank=True, default=False, help_text='Used for First Time Registration.', null=True),
        ),
    ]
