# Generated by Django 2.2.7 on 2019-11-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_auto_20191123_0907'),
        ('initial', '0024_auto_20191123_0907'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesheet',
            unique_together={('student', 'scsddc')},
        ),
        migrations.AlterUniqueTogether(
            name='marksheet',
            unique_together={('student', 'scsddc')},
        ),
    ]
