# Generated by Django 2.2.7 on 2019-11-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0025_auto_20191124_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesection',
            old_name='CSDDC',
            new_name='scsddc',
        ),
    ]
