# Generated by Django 2.2.7 on 2019-11-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_auto_20191123_0907'),
        ('initial', '0026_auto_20191124_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_interval_allowed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_marked_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_slot',
            field=models.CharField(blank=True, choices=[(1, '8:00 AM - 9:00'), (2, '9:00 AM- 10:00'), (3, '10:00 AM- 11:00 PM'), (4, '11:00 AM- 12:00 PM'), (5, '12:00 PM- 1:00 PM'), (6, '1:00 PM- 2:00 PM'), (7, '2:00 PM- 3:00 PM'), (8, '3:00 PM- 4:00 PM')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(blank=True, choices=[('M', 'Manual'), ('QR', 'QR-Code')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='duration_hour',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='qr_change_interval',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scsddc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='scsddc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'scsddc', 'class_date', 'attendance_slot')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='duration',
        ),
    ]
