# Generated by Django 2.2.7 on 2019-11-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0028_auto_20191125_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionattendance',
            name='attendance_interval_allowed',
            field=models.PositiveSmallIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='sectionattendance',
            name='attendance_time_start',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionattendance',
            name='class_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sectionattendance',
            name='qr_change_interval',
            field=models.PositiveSmallIntegerField(blank=True, default=1800, null=True),
        ),
    ]
