# Generated by Django 2.2.7 on 2019-11-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_auto_20191123_0907'),
        ('initial', '0029_auto_20191125_0903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='StudentMarks',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='attendance_sheet',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='mark_sheet',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='students',
        ),
        migrations.CreateModel(
            name='StudentInfoSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_sheet', models.ManyToManyField(to='initial.AttendanceSheet')),
                ('mark_sheet', models.ManyToManyField(to='initial.MarkSheet')),
                ('student', models.ManyToManyField(to='student_portal.Student')),
            ],
        ),
        migrations.AddField(
            model_name='coursesection',
            name='student_info',
            field=models.ManyToManyField(blank=True, null=True, to='initial.StudentInfoSection'),
        ),
    ]
