# Generated by Django 2.2.7 on 2020-01-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0031_auto_20191127_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='section_total_seats',
            field=models.PositiveIntegerField(blank=True, default=40, help_text='Total Seats : Seats Left + students Registered', null=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='students_count',
            field=models.PositiveIntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='section_seats',
            field=models.PositiveIntegerField(blank=True, default=40, help_text='Seats Left', null=True),
        ),
    ]
