# Generated by Django 2.2.7 on 2020-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0032_auto_20200106_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
