# Generated by Django 2.2.7 on 2020-01-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0033_auto_20200106_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='weightage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='grand_total_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='mark_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='obtained_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='total_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SectionMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_type', models.CharField(max_length=256)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('weightage', models.FloatField(blank=True, null=True)),
                ('scsddc', models.CharField(blank=True, max_length=256, null=True)),
                ('section', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'unique_together': {('scsddc', 'marks_type', 'section')},
            },
        ),
    ]
