# Generated by Django 2.2 on 2020-04-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0034_auto_20200111_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-semester_code']},
        ),
        migrations.AddField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='initial.Course'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='student_info',
            field=models.ManyToManyField(to='initial.StudentInfoSection'),
        ),
    ]
