# Generated by Django 2.2 on 2020-04-13 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0035_auto_20200414_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ['-scsddc']},
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='student_info',
        ),
        migrations.AddField(
            model_name='coursesection',
            name='student_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='initial.StudentInfoSection'),
        ),
    ]
