# Generated by Django 2.2 on 2020-04-15 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0036_auto_20200414_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionattendance',
            name='class_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='class_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
