# Generated by Django 2.2 on 2020-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0037_auto_20200415_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='average',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='maximum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='minimum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='standard_devition',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='student_info',
        ),
        migrations.AddField(
            model_name='coursesection',
            name='student_info',
            field=models.ManyToManyField(to='initial.StudentInfoSection'),
        ),
    ]
