# Generated by Django 2.2 on 2020-05-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0038_auto_20200510_1114'),
        ('initial', '0038_auto_20200513_0031'),
    ]

    operations = [
    ]
