# Generated by Django 2.2 on 2020-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0039_merge_20200514_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='current_semester',
            field=models.BooleanField(default=True),
        ),
    ]
