# Generated by Django 2.2 on 2020-05-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0039_merge_20200515_2314'),
        ('initial', '0040_semester_current_semester'),
    ]

    operations = [
    ]
