# Generated by Django 2.2 on 2020-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0043_auto_20200522_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='grand_total_marks',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
