# Generated by Django 2.2 on 2020-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0044_auto_20200522_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='obtained_weightage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='obtained_marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
