# Generated by Django 2.2 on 2020-05-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0045_auto_20200523_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='semester_season',
            field=models.SmallIntegerField(choices=[(1, 'SPRING'), (2, 'FALL'), (3, 'SUMMER')], default=1),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regularcorecourseload',
            name='semester_season',
            field=models.SmallIntegerField(choices=[(1, 'SPRING'), (2, 'FALL'), (3, 'SUMMER')]),
        ),
        migrations.AlterField(
            model_name='regularelectivecourseload',
            name='semester_season',
            field=models.SmallIntegerField(choices=[(1, 'SPRING'), (2, 'FALL'), (3, 'SUMMER')]),
        ),
        migrations.AlterField(
            model_name='repeatcourseload',
            name='semester_season',
            field=models.SmallIntegerField(choices=[(1, 'SPRING'), (2, 'FALL'), (3, 'SUMMER')]),
        ),
    ]
