# Generated by Django 2.2 on 2020-05-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0012_feechallan_payment_date'),
        ('initial', '0046_auto_20200526_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='initial.Course'),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='gpa',
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='grade',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='obtained_marks',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='grand_total_marks',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_season',
            field=models.SmallIntegerField(choices=[(2, 'FALL'), (1, 'SPRING'), (3, 'SUMMER')]),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgpa', models.FloatField(blank=True, default=0.0, max_length=6, null=True)),
                ('cgpa', models.FloatField(blank=True, default=0.0, max_length=6, null=True)),
                ('credit_hours_earned', models.IntegerField(blank=True)),
                ('credit_hours_attempted', models.IntegerField(blank=True)),
                ('last', models.BooleanField(default=False)),
                ('course_result', models.ManyToManyField(to='initial.MarkSheet')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='initial.Semester')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_portal.Student')),
            ],
        ),
    ]
