# Generated by Django 2.2 on 2020-05-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0047_auto_20200527_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='credit_hours_attempted',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='credit_hours_earned',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
