# Generated by Django 2.2 on 2020-05-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0048_auto_20200527_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-course_name',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_short',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_code',
            field=models.CharField(default='SPRING2020', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_season',
            field=models.SmallIntegerField(choices=[(1, 'SPRING'), (2, 'FALL'), (3, 'SUMMER')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='attendance_slot',
            field=models.CharField(blank=True, choices=[(1, '8:00 AM - 9:00 PM'), (2, '9:00 AM - 10:00 PM'), (3, '10:00 AM - 11:00 PM'), (4, '11:00 AM - 12:00 PM'), (5, '12:00 PM - 1:00 PM'), (6, '1:00 PM - 2:00 PM'), (7, '2:00 PM - 3:00 PM'), (8, '3:00 PM - 4:00 PM')], max_length=256, null=True),
        ),
    ]
