# Generated by Django 2.2 on 2020-05-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0049_auto_20200529_1020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offeredcourses',
            unique_together=set(),
        ),
    ]
