# Generated by Django 2.2 on 2020-05-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0012_feechallan_payment_date'),
        ('initial', '0050_auto_20200530_0215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offeredcourses',
            unique_together={('semester_code', 'student')},
        ),
    ]
