# Generated by Django 2.2 on 2020-05-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0051_auto_20200530_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='student_info',
            field=models.ManyToManyField(blank=True, to='initial.StudentInfoSection'),
        ),
    ]
