# Generated by Django 2.2 on 2020-05-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0053_auto_20200530_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='course_result',
            field=models.ManyToManyField(blank=True, to='initial.MarkSheet'),
        ),
    ]
