# Generated by Django 2.2 on 2020-05-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0049_auto_20200530_1304'),
        ('initial', '0054_auto_20200530_1011'),
    ]

    operations = [
    ]
