# Generated by Django 2.2 on 2020-06-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0055_merge_20200530_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmarks',
            name='max_marks',
            field=models.FloatField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='sectionmarks',
            name='min_marks',
            field=models.FloatField(blank=True, default=0, max_length=10),
        ),
    ]
