# Generated by Django 2.2.5 on 2019-09-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20190910_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty Supervisors'},
        ),
    ]
