# Generated by Django 2.2.5 on 2019-09-10 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0006_user_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CNIC',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{5}-[0-9]{7}-[0-9]{1}$', message='Invalid CNIC')]),
        ),
    ]
