# Generated by Django 2.2.5 on 2019-09-12 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0007_auto_20190910_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_maintainer',
            field=models.BooleanField(default=False, help_text='True if the User is a Mainatiner or Project Developer.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='CNIC',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[0-9]{5}-[0-9]{7}-[0-9]{1}', message='Invalid CNIC')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_faculty',
            field=models.BooleanField(default=False, help_text='True if the User is a Faculty Member.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='True if the User is a Student.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='True if the User is a Teacher.'),
        ),
    ]
