# Generated by Django 2.2.5 on 2019-09-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0009_auto_20190914_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ARN',
            field=models.PositiveIntegerField(verbose_name='Admission Registration Number'),
        ),
    ]
