# Generated by Django 2.2.5 on 2019-09-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0010_auto_20190914_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ARN',
        ),
    ]
