# Generated by Django 2.2.5 on 2019-09-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0011_remove_student_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ARN',
            field=models.PositiveIntegerField(null=True, verbose_name='Admission Registration Number'),
        ),
    ]
