# Generated by Django 2.2.5 on 2019-09-16 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campuses',
            name='name',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(default='00K-0000', help_text='University Student Roll Number', max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[0-9]{2}[KLFICP]-[0-9]{4}', message='INVALID ROLL NUMBER FORMAT')], verbose_name='Student ID'),
        ),
        migrations.DeleteModel(
            name='Campuses',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
