# Generated by Django 2.2.5 on 2019-09-28 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20190916_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='arn',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Admission Registration Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(default='00K-0000', help_text='University Student Roll Number', max_length=8, validators=[django.core.validators.RegexValidator('[0-9]{2}[KLFICP]-[0-9]{4}', message='INVALID ROLL NUMBER FORMAT')], verbose_name='Student ID'),
        ),
    ]
