# Generated by Django 2.2.5 on 2019-09-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20190910_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_admin',
            new_name='is_admin',
        ),
    ]
