# Generated by Django 2.2.6 on 2019-11-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='highest_qualification',
            field=models.CharField(choices=[(1, 'Bachelors'), (2, 'Masters'), (3, 'Doctrate')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
