# Generated by Django 2.2.6 on 2019-11-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0002_auto_20191109_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='highest_qualification',
            field=models.SmallIntegerField(choices=[(1, 'Bachelors'), (2, 'Masters'), (3, 'Doctrate')], max_length=256, null=True),
        ),
    ]
