# Generated by Django 2.2.6 on 2019-11-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0004_auto_20191109_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
