# Generated by Django 2.2.5 on 2019-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20190914_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ARN',
            field=models.PositiveIntegerField(default=1248, verbose_name='Admission Registration Number'),
            preserve_default=False,
        ),
    ]
