# Generated by Django 2.2.5 on 2019-09-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_auto_20190914_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ARN',
            field=models.PositiveIntegerField(null=True, verbose_name='Admission Registration Number'),
        ),
    ]
