# Generated by Django 2.2.5 on 2019-09-09 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id_n', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z][0-9]{2}-[0-9]{4}$', message='Invalid Student ID')])),
            ],
        ),
    ]
