# Generated by Django 2.2.5 on 2019-09-09 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id_n',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z][0-9]{2}-[0-9]{4}$', message='Invalid Student ID')]),
        ),
    ]
