# Generated by Django 2.2.5 on 2019-09-09 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0006_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nu_email',
            field=models.CharField(default='No_MAIL', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
